### ISSUE TITLE
Issue Connecting to Server

### ISSUE THREAD

**Issue by mragonese** [objcio/issue-10-core-data-network-application#1]
I really enjoyed the tutorial (http://www.objc.io/issue-10/networked-core-data-application.html), but unfortunately the web service that it's based upon doesn't seem to be up-and-running. Is there any way to fix this to ensure a valid JSON response? The invalid URL is http://localhost:4567/specs?page=0.

**Comment by hayyyyyyden** [comment]
+1. I encountered the same issue. The example code not work.

**Comment by chriseidhof** [comment]
Yes, you need to run a local web server. See https://gist.github.com/chriseidhof/725946f0d02b17ced209 for how to set it up!
