### ISSUE TITLE
Service on localhost doesn't exist

### ISSUE THREAD

**Issue by npollitt** [objcio/issue-10-core-data-network-application#2]
Hello, I forked this project and ran it in the simulator to go along with the objcio article.  But the app doesn't do anything when I run it.  I see it's requesting data from http://localhost:4567, but I don't have any services running on my machine on that port.

**Comment by rmolsbee** [comment]
https://gist.github.com/chriseidhof/725946f0d02b17ced209 

Create a file called app.rb and paste the contents of the aforementioned gist. Might have to add a line to bind to an ip other than localhost to run on an actual device. Fire it up with ruby app.rb and the pages will start coming in.

**Comment by npollitt** [comment]
Had a couple more steps to get this working:
sudo gem install sinatra
git clone https://github.com/CocoaPods/Specs.git

Now it works.  Thank you.
